# Generated by Django 5.0.7 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('receipt_no',)},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Khaja Bagh', 'Khaja Bagh'), ('Akber Bagh', 'Akber Bagh'), ('Ghatkesar', 'Ghatkesar'), ('Bandlaguda', 'Bandlaguda')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Mahade Ashraf', 'Mahade Ashraf'), ('معہد علیم', 'معہد علیم'), ('معہد ابرار', 'معہد ابرار'), ('معہد قاسم', 'معہد قاسم'), ('حفظ', 'حفظ'), ('ناظرہ', 'ناظرہ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('INTER - I', 'INTER - I'), ('INTER - II', 'INTER - II'), ('B.COM - I', 'B.COM - I'), ('B.COM - II', 'B.COM - II'), ('B.COM - III', 'B.COM - III'), ('Awwal (Alif)', 'اول (الف)'), ('Awwal (Baa)', 'اول (ب)'), ('Awwal (Jeem)', 'اول (ج)'), ('Duwwam (Alif)', 'دوم (الف)'), ('Duwwam (Baa)', 'دوم (ب)'), ('Suwwam (Alif)', 'سوم (الف)'), ('Suwwam (Baa)', 'سوم (ب)'), ('Suwwam (Jeem)', 'سوم (ج)'), ('Chahrum (Alif)', 'چهارم (الف)'), ('Chahrum (Baa)', 'چهارم (ب)'), ('Panjum', 'پنجم'), ('Mouqoof Alai', 'موقوف علیہ'), ('Daur-e-Hadees', 'دورہ حدیث'), ('Edadiya School (Alif)', 'ادادیہ اسکول (الف)'), ('Edadiya School (Baa)', 'ادادیہ اسکول (ب)'), ('Awwal School (Alif)', 'اول اسکول (الف)'), ('Awwal School (Baa)', 'اول اسکول (ب)'), ('Duwwam School (Alif)', 'دوم اسکول (الف)'), ('Duwwam School (Baa)', 'دوم اسکول (ب)'), ('Suwwam', 'سوم'), ('Chahrum', 'چهارم'), ('Hifz-Alif', 'Hifz-Alif'), ('Hifz-Baa', 'Hifz-Baa'), ('Hifz-Jeem', 'Hifz-Jeem'), ('Hifz-Daal', 'Hifz-Daal'), ('Hifz-Zaa', 'Hifz-Zaa'), ('Hifz-Haa', 'Hifz-Haa'), ('Hifz-Haah', 'Hifz-Haah'), ('Hifz-Waav', 'Hifz-Waav'), ('Nazira-Alif', 'Nazira-Alif'), ('Nazira-Baa', 'Nazira-Baa'), ('Nazira-Jeem', 'Nazira-Jeem'), ('Nazira-Daal', 'Nazira-Daal')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='book_no',
        ),
    ]
